Ensure dnsimple.Record works in all languages
Fixes: #76

The ttl and priority types of dnsimple.Record where incorrectly
set as int when the DNSimple API returned strings for these. This
caused the following error in CSharp

```
    error: Running program '/Users/stack72/code/dnsimple-check/dnsimple-csharp/bin/Debug/netcoreapp3.1/dnsimple-csharp.dll' failed with an unhandled exception:
    System.InvalidOperationException: Expected System.Double but got System.String deserializing Pulumi.DNSimple.Record.ttl
       at Pulumi.Serialization.Converter.ConvertObject(String context, Object val, Type targetType)
       at Pulumi.Serialization.Converter.ConvertValue(String context, Value value, Type targetType, ImmutableHashSet`1 resources)
       at Pulumi.Deployment.CompleteResourceAsync(Resource resource, Boolean remote, Func`2 newDependency, ResourceArgs args, ResourceOptions options, ImmutableDictionary`2 completionSources)
       at Pulumi.Deployment.Runner.<>c__DisplayClass9_0.<<WhileRunningAsync>g__HandleCompletion|0>d.MoveNext()
```

CSharp is much more strict about this than the other languages but we
can see from the a stack export with TypeScript that the outputs are
actually strings:

```
                "outputs": {
                    "id": "23466833",
                    "name": "test",
                    "priority": "0",
                    "ttl": "3600",
                    "type": "A",
                    "value": "192.168.0.11"
                },
```

Removing these type overrides from the provider resource is a slight
breaking change for the provider but this is a breaking change that
means the resource works correctly and *WILL NOT* force an upgrade

I have included new tests to ensure this is the case